"""
Dashboard Components
====================

Visualization and tracking components for the trading system dashboard.
"""

from __future__ import annotations

from dashboard.components.event_flow import (
    EventFlowRecord,
    EventFlowTracker,
    FlowStatistics,
    AgentConnection,
)
from dashboard.components.agent_status import (
    AgentStatus,
    AgentType,
    AgentStatusRecord,
    AgentHealthMetrics,
    AgentStatusTracker,
    AGENT_TYPE_MAPPING,
)
from dashboard.components.decision_tracker import (
    DecisionTracker,
    DecisionRecord,
    DecisionStatistics,
    DecisionOutcome,
    DecisionAction,
)
from dashboard.components.signal_aggregation import (
    SignalRecord,
    AggregatedSignal,
    AgentSignalStats,
    HeatmapCell,
    SignalAggregator,
    ConsensusDirection,
    SIGNAL_AGENTS,
)
from dashboard.components.backtest_view import (
    BacktestResult,
    BacktestViewer,
    BacktestComparison,
    TradeRecord,
    TradeAnalysis,
    MonteCarloResult,
    MarketCondition,
    TradeDirection,
    EquityCurvePoint,
)
from dashboard.components.compliance_view import (
    ComplianceView,
    ComplianceStatus,
    ViolationRecord,
    BlackoutPeriod,
    RestrictedInstrument,
    RegulatorySummary,
    CheckStatus,
    ViolationSeverity,
    ViolationType,
    ResolutionStatus,
    REGULATION_REFERENCES,
)
from dashboard.components.llm_analytics import (
    LLMAnalytics,
    LLMRequest,
    LLMUsageStats,
    LLMProvider,
    LLMPurpose,
    RateLimitStatus,
    DailyUsage,
)
from dashboard.components.audit_viewer import (
    AuditEntry,
    AuditEntryType,
    AuditFilter,
    AuditViewer,
)
from dashboard.components.system_health import (
    ComponentHealth,
    ComponentStatus,
    SystemMetrics,
    HealthHistoryEntry,
    HealthAlert,
    AlertSeverity,
    UptimeReport,
    SystemHealthMonitor,
)
from dashboard.components.social_research import (
    Platform,
    SentimentCategory,
    SocialPost,
    SocialSentiment,
    TrendingTopic,
    InfluencerActivity,
    SocialAlert,
    SentimentAnalyzer,
    SocialResearchTracker,
    MockTwitterAPI,
    MockRedditAPI,
    MockStockTwitsAPI,
)
from dashboard.components.performance_metrics import (
    PerformanceMetrics,
    RollingPeriod,
    DailyPnL,
    EquityCurvePoint as PerformanceEquityCurvePoint,
    RollingMetrics,
    BenchmarkComparison,
    PerformanceTradeRecord,
    PERIOD_DAYS,
)
from dashboard.components.config_manager import (
    ConfigManager,
    ConfigSection,
    ConfigParameter,
    ConfigChange,
    ParameterType,
    DangerLevel,
    ChangeStatus,
    create_config_manager,
)
from dashboard.components.position_view import (
    AssetType,
    PositionRecord,
    PortfolioSummary,
    PositionHistoryPoint,
    PositionView,
)
from dashboard.components.market_data_view import (
    MarketDataView,
    QuoteData,
    OHLCBar,
    MarketOverview,
    PriceAlert,
    AlertNotification,
    AlertType,
    TimeFrame,
    InstrumentType,
    TIMEFRAME_SECONDS,
)
from dashboard.components.alerts import (
    AlertManager,
    Alert,
    AlertRule,
    AlertSeverity as DashboardAlertSeverity,
    AlertCategory,
    AlertState,
    create_alert_manager,
    create_builtin_rules,
)
from dashboard.components.ai_model_status import (
    ModelType,
    ModelStatus,
    DRLModelMetrics,
    TFTModelMetrics,
    FinBERTMetrics,
    LLMMetrics,
    ModelInfo,
    ModelSystemHealth,
    AIModelTracker,
    create_drl_model_card,
    create_tft_model_card,
    create_finbert_model_card,
    create_llm_model_card,
)
from dashboard.components.daily_report import (
    DailyReport,
    DailyReportGenerator,
    ExecutiveSummary,
    PerformanceSection,
    PositionsSection,
    PositionEntry,
    DecisionsSection,
    DecisionEntry,
    SignalsSection,
    SignalSummary,
    RiskSection,
    RecommendationsSection,
    Recommendation,
    IssuesSection,
    Issue,
    ReportStatus,
    AlertSeverity as ReportAlertSeverity,
)

__all__ = [
    # Event Flow
    "EventFlowRecord",
    "EventFlowTracker",
    "FlowStatistics",
    "AgentConnection",
    # Agent Status
    "AgentStatus",
    "AgentType",
    "AgentStatusRecord",
    "AgentHealthMetrics",
    "AgentStatusTracker",
    "AGENT_TYPE_MAPPING",
    # Decision Tracking
    "DecisionTracker",
    "DecisionRecord",
    "DecisionStatistics",
    "DecisionOutcome",
    "DecisionAction",
    # Signal Aggregation
    "SignalRecord",
    "AggregatedSignal",
    "AgentSignalStats",
    "HeatmapCell",
    "SignalAggregator",
    "ConsensusDirection",
    "SIGNAL_AGENTS",
    # Backtest View
    "BacktestResult",
    "BacktestViewer",
    "BacktestComparison",
    "TradeRecord",
    "TradeAnalysis",
    "MonteCarloResult",
    "MarketCondition",
    "TradeDirection",
    "EquityCurvePoint",
    # Compliance View
    "ComplianceView",
    "ComplianceStatus",
    "ViolationRecord",
    "BlackoutPeriod",
    "RestrictedInstrument",
    "RegulatorySummary",
    "CheckStatus",
    "ViolationSeverity",
    "ViolationType",
    "ResolutionStatus",
    "REGULATION_REFERENCES",
    # LLM Analytics
    "LLMAnalytics",
    "LLMRequest",
    "LLMUsageStats",
    "LLMProvider",
    "LLMPurpose",
    "RateLimitStatus",
    "DailyUsage",
    # Audit Viewer
    "AuditEntry",
    "AuditEntryType",
    "AuditFilter",
    "AuditViewer",
    # System Health
    "ComponentHealth",
    "ComponentStatus",
    "SystemMetrics",
    "HealthHistoryEntry",
    "HealthAlert",
    "AlertSeverity",
    "UptimeReport",
    "SystemHealthMonitor",
    # Social Research
    "Platform",
    "SentimentCategory",
    "SocialPost",
    "SocialSentiment",
    "TrendingTopic",
    "InfluencerActivity",
    "SocialAlert",
    "SentimentAnalyzer",
    "SocialResearchTracker",
    "MockTwitterAPI",
    "MockRedditAPI",
    "MockStockTwitsAPI",
    # Performance Metrics
    "PerformanceMetrics",
    "RollingPeriod",
    "DailyPnL",
    "PerformanceEquityCurvePoint",
    "RollingMetrics",
    "BenchmarkComparison",
    "PerformanceTradeRecord",
    "PERIOD_DAYS",
    # Config Manager
    "ConfigManager",
    "ConfigSection",
    "ConfigParameter",
    "ConfigChange",
    "ParameterType",
    "DangerLevel",
    "ChangeStatus",
    "create_config_manager",
    # Position View
    "AssetType",
    "PositionRecord",
    "PortfolioSummary",
    "PositionHistoryPoint",
    "PositionView",
    # Market Data View
    "MarketDataView",
    "QuoteData",
    "OHLCBar",
    "MarketOverview",
    "PriceAlert",
    "AlertNotification",
    "AlertType",
    "TimeFrame",
    "InstrumentType",
    "TIMEFRAME_SECONDS",
    # Alerts
    "AlertManager",
    "Alert",
    "AlertRule",
    "DashboardAlertSeverity",
    "AlertCategory",
    "AlertState",
    "create_alert_manager",
    "create_builtin_rules",
    # AI Model Status
    "ModelType",
    "ModelStatus",
    "DRLModelMetrics",
    "TFTModelMetrics",
    "FinBERTMetrics",
    "LLMMetrics",
    "ModelInfo",
    "ModelSystemHealth",
    "AIModelTracker",
    "create_drl_model_card",
    "create_tft_model_card",
    "create_finbert_model_card",
    "create_llm_model_card",
    # Daily Report
    "DailyReport",
    "DailyReportGenerator",
    "ExecutiveSummary",
    "PerformanceSection",
    "PositionsSection",
    "PositionEntry",
    "DecisionsSection",
    "DecisionEntry",
    "SignalsSection",
    "SignalSummary",
    "RiskSection",
    "RecommendationsSection",
    "Recommendation",
    "IssuesSection",
    "Issue",
    "ReportStatus",
    "ReportAlertSeverity",
]
